import matplotlib.pyplot as plt
from baseline_classificacao import baseC
from ensemble_classificacao import ensembleC
from stacking_classficacao import stackingC
from baseline_regresssao import baseR
from ensemble_regressao import ensembleR
from stacking_regressao import stackingR

def main():
    print('\nAlgoritmo baseline classificação')
    fechamentos,riqueza = baseC('PETR3.SA')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_baseline_classificação.png', format='png')

    print('\nAlgoritmo ensemble votação classificação')
    fechamentos,riqueza = ensembleC('PETR3.SA', tipo = 'votação')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_ensemble_votacao_classificação.png', format='png')

    print('\nAlgoritmo ensemble media classificação')
    fechamentos,riqueza = ensembleC('PETR3.SA', tipo = 'media')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_ensemble_media_classificação.png', format='png')

    print('\nAlgoritmo ensemble media ponderada classificação')
    fechamentos,riqueza = ensembleC('PETR3.SA', tipo = 'media ponderada')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_ensemble_mediaPonderada_classificação.png', format='png')

    print('\nAlgoritmo stacking classificação')
    fechamentos,riqueza = stackingC('PETR3.SA')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_stacking_classificação.png', format='png')

    print('\nAlgoritmo baseline regressao')
    fechamentos,riqueza = baseR('PETR3.SA')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_baseline_regressão.png', format='png')

    print('\nAlgoritmo ensemble media regressão')
    fechamentos,riqueza = ensembleR('PETR3.SA', tipo = 'media')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_ensemble_media_regressão.png', format='png')

    print('\nAlgoritmo ensemble media ponderada regressão')
    fechamentos,riqueza = ensembleR('PETR3.SA', tipo = 'media ponderada')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_ensemble_mediaPonderada_regressão.png', format='png')

    print('\nAlgoritmo ensemble votação regressão')
    fechamentos,riqueza = stackingR('PETR3.SA')
    plt.figure(figsize=(12, 6))
    plt.plot(fechamentos, label='Fechamento', marker='')
    plt.plot(riqueza, label='Riqueza', marker='')
    plt.xlabel('Dia')
    plt.ylabel('Valor')
    plt.title('Evolução do Fechamento e Riqueza ao longo do tempo')
    plt.legend()
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('graficos/grafico_stacking_regressão.png', format='png')

main()